package my.javaee.ejb.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-01-29T14:29:16.200+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://beans.ejb.javaee.my/", name = "PropertyBean")
@XmlSeeAlso({ObjectFactory.class})
public interface PropertyBean {

    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean create(
        @WebParam(name = "arg0", targetNamespace = "")
        my.javaee.ejb.beans.Property arg0
    );

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        my.javaee.ejb.beans.Property arg0
    );

    @WebMethod
    @RequestWrapper(localName = "read", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.ReadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public my.javaee.ejb.beans.Property read(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "list", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<my.javaee.ejb.beans.Property> list(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://beans.ejb.javaee.my/", className = "my.javaee.ejb.beans.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
