package my.javaee.ejb.beans;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-01-29T14:29:16.262+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "PropertyBeanService", 
                  wsdlLocation = "file:/C:/Users/hi/eclipse-workspace/hans.ws/wsdl/property.wsdl",
                  targetNamespace = "http://beans.ejb.javaee.my/") 
public class PropertyBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://beans.ejb.javaee.my/", "PropertyBeanService");
    public final static QName PropertyBeanPort = new QName("http://beans.ejb.javaee.my/", "PropertyBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/hi/eclipse-workspace/hans.ws/wsdl/property.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PropertyBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/hi/eclipse-workspace/hans.ws/wsdl/property.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PropertyBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PropertyBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PropertyBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PropertyBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PropertyBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PropertyBean
     */
    @WebEndpoint(name = "PropertyBeanPort")
    public PropertyBean getPropertyBeanPort() {
        return super.getPort(PropertyBeanPort, PropertyBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyBean
     */
    @WebEndpoint(name = "PropertyBeanPort")
    public PropertyBean getPropertyBeanPort(WebServiceFeature... features) {
        return super.getPort(PropertyBeanPort, PropertyBean.class, features);
    }

}
